### PR TITLE
add deps to deps

### PR DESCRIPTION
**Pull request by aminya**
When you are using something you should add it to the deps.

### CODE REVIEW

**Comment by Alhadis** [comment]
`event-kit ` is already bundled with Atom, and accessible through the `atom` "module":

~~~js
const {CompositeDisposable, Emitter} = require("atom");
~~~

**Comment by aminya** [comment]
image

**Comment by Alhadis** [comment]
Where exactly are you seeing this? Can you copy+paste the stack trace?

**Comment by Alhadis** [comment]
Ah wait, sorry, I didn't notice you'd filed this on the `mapped-disposable` repository.

You'll need to add `event-kit` as a dependency manually if your project isn't Atom-related. I don't know why I promulgated this module as reusable in other environments…

The `event-kit` module is [loaded like this](https://github.com/aminya/mapped-disposable/blob/57d34aa4719851cff0c561039870f5d98083e496/index.js#L3-L5). The reason it's not added as a hard dependency is that it would result in `event-kit` being downloaded and installed irrespective of whether it's running in Atom or not. Less resources, less fragmentation, etc.

**Comment by aminya** [comment]
Adding `event-kit` to the dependencies does not interfere with anything. It is just a folder that is downloaded to `node_modules`. You should add it to the deps. I faced the issue, soon I tried to use the package in a non-conventional way.
or if you don't want to simplify the code to:
```js
const {CompositeDisposable, Disposable} = require("atom")
```
This way of using `require` is hacky and breaks the code compilers.

**Comment by Alhadis** [comment]
It also simplifies running tests, which I'm able to do in Node.js without the overhead of a full Atom environment.

> It is just a folder that is downloaded to `node_modules`.

Given how many times `apm` has [timed out](https://github.com/file-icons/atom/issues?q=label%3Ainstallation+) whilst downloading an update, I don't think inflating installation time with one more object to fetch/extract after an update is a very good idea. Especially when it's redundant anyway.

**Pull request closed without merging**
